### ISSUE TITLE
Chrome thinks app is in Norwegian

### ISSUE THREAD

**Issue by stuartlangridge** [01org/webapps-scientific-calculator#31]
Visiting this app in android Chrome, I get a pop-up suggesting that the page is in Norwegian and offering to translate. I suspect this can be avoided by explicitly specifying <html lang="en">, but you'll want to test that.

**Comment by davidmaxwaterman** [comment]
Yes, I've seen that. I've asked around but people suggest that isn't possible. If you (or anyone else reading this) knows otherwise, I'm very happy to implement any change necessary.

**Comment by davidmaxwaterman** [comment]
For the record, the line is :

```
    <meta name="google" value="notranslate"/>
```

Tested using incognito mode on desktop - the little 'translate' icon is no longer shown.

Fixed in 7a280f650804dd8af908d10187654be750b74922.

Thanks for reporting this. Closing.
